config/routes.rb
Rails.application.routes.draw do

  #Initialize devise routes
  devise_for :players

  #Pusher authentication mode //subscribe to private channels

    post "pusher/auth"


  #Play and Nested resources
  root to: 'plays#index'
  resources :plays do
    resources :messages, only: [:index, :show, :create]
    resources :moves, only: [:show, :create]
  end

  #Player profile
  get '/:id', to: 'players#show', as: :player

end

app/models/play.rb
class Play < ActiveRecord::Base

  #Include Redis
  include Redis::Objects

  #Associations
  has_many :messages, dependent: :destroy
  belongs_to :player
  belongs_to :opponent, foreign_key: 'opponent_id', class_name: 'Player'
  belongs_to :looser, foreign_key: 'looser_id', class_name: 'Player'
  belongs_to :winner, foreign_key: 'winner_id', class_name: 'Player'

  # Basic validation
  validates_presence_of :player_id, :opponent_id, :min_moves

  # Callback to update play and player counters
  after_commit :update_counters, :update_winners, if: :completed?, on: :update

  # Redis fields and counters
  counter :player_score
  value :last_move_id
  counter :opponent_score
  counter :moves_count

  #Public interface methods

  public

  # Check if play is completed
  def completed?
    min_moves == moves_count.value
  end

  # Check if play is draw
  def draw?
    return false unless completed?
    player_score.value == opponent_score.value
  end

  # Find winning player based on score
  def winning_player_id
    return nil if draw?
    player_score.value > opponent_score.value ? player_id : opponent_id
  end

  # Find loosing player
  def loosing_player_id
    return nil if draw?
    winning_player_id == player_id ? opponent_id : player_id
  end

  # Update redis counters once play completed
  def update_counters
    player.plays_count.increment
    opponent.plays_count.increment
    true
  end

  # Update redis counters for winner and looser
  def update_winners
    return true if draw?
    winner.wins_count.increment
    Player.rank.incr(winner.id)
    looser.loose_count.increment
    true
  end

  # Check if play completed
  def player_status(player)
    return "Draw" if draw?
    player.id == winner_id ? "Won" : "Lost"
  end

  # Check if moves completed
  def not_played_by?(player)
    opponent?(player) ?
      opponent_moves.last.opponent_choice.nil? :
      player_moves.last.player_choice.nil?
  end

  # Find opponent moves
  def opponent_moves
    opponent.opponent_moves.order(id: :asc).where(play_id: self.id) if opponent_id.present?
  end

  # Find player moves
  def player_moves
    player.moves.order(id: :asc).where(play_id: self.id) if player_id.present?
  end

  # Check if opponent
  def opponent?(player)
    opponent_id == player.id
  end

end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :authenticate_player!, except: :index
  before_action :set_play, only: [:show, :edit, :update, :destroy]
  before_action :current_user

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.includes(:opponent, :player, :winner).all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
    authorize @play
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)
    @play.player = current_player
    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url, notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def current_user
      current_player
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.includes(:player, :opponent, :winner, :messages).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:opponent_id, :min_moves)
    end
end

app/views/plays/_form.html.erb
<%= form_for(@play) do |f| %>
  <div class="p-l-15 p-r-15">
    <% if @play.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@play.errors.count, "error") %> prohibited this play from being saved:</h2>
        <ul>
          <% @play.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :min_moves, "Set Moves (ODD)" %><br />
      <%= f.text_field :min_moves, class: 'form-control p-l-15 p-r-15' %>
    </div>
    <div class="form-group">
      <%= f.label :opponent_id, "Choose opponnent" %><br />
      <%= f.collection_select :opponent_id, Player.where.not(id: current_player.id), :id, :name, {prompt: true},  {class: 'form-control'} %>
    </div>
    <div class="actions">
      <%= f.submit "Play", class: 'btn btn-success m-r-10' %>
      <%= link_to 'Back', plays_path, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/plays/index.html.erb
<div class="outer">
  <div class="clearfix">
    <div class="pull-left">
      <h1 class="title">Recent Plays</h1>
    </div>
    <%= link_to('New Play', new_play_path, class: 'btn btn-success pull-right') %>
  </div>
  <div class="play-header selected m-t-20">
    <div class="col-sm-5 no-padding m-t-10">
      <span class="name">Player</span>
      <span class="badge">vs</span>
      <span class="name">Opponent</span>
    </div>
    <span class="score">Score</span>
  </div>
  <div class="leaderboard">
    <% @plays.each do |play| %>
      <%= link_to(play_path(play)) do %>
        <div class="play">
          <span class="name"><%= play.player.name %></span>
          <span class="badge" id="vs"> vs </span>
          <span class="name"><%= play.opponent.name %></span>
          <span class="score"><%= play.player_score.value %>:<%= play.opponent_score.value %></span>
          <% if play.completed? and !play.draw? %>
            <p class="description"><%= play.winner.name %> defeated <%= play.looser.name %></p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/plays/new.html.erb
<div class="game">
  <div class="col-sm-4 m-t-50 auto-margin">
    <%= render 'form' %>
  </div>
</div>

app/views/plays/show.html.erb
<div class="game">
  <div class="row clearfix m-t-50">
    <div class="chat">
      <%= react_component('Messages', {messages: render(template: 'messages/index.json.jbuilder', locals: {messages: @play.messages}), game_channel: "play_#{@play.id}_chat", play_id: @play.id, path: play_messages_path(@play.id)}) %>
    </div>
    <%= react_component('Game', { play: render(template: 'plays/show.json.jbuilder'), game_channel: "play_#{@play.id}", path: play_moves_path(@play.id)} ) %>
  </div>
</div>